import type { CVTemplate } from "@/lib/supabase/types";

export const cvTemplates: CVTemplate[] = [
  {
    id: "moderno",
    name: "Moderno",
    description: "Design pulito con colori scuri e accenti gradient",
    accentColor: "#818cf8",
    bgColor: "#1e293b",
    textColor: "#f8fafc",
    secondaryText: "#94a3b8",
    fontFamily: "Inter, system-ui, sans-serif",
    layout: "single-column",
    headerStyle: "gradient-bar",
    skillsStyle: "tags",
  },
  {
    id: "classico",
    name: "Classico",
    description: "Layout tradizionale professionale",
    accentColor: "#1e40af",
    bgColor: "#ffffff",
    textColor: "#1f2937",
    secondaryText: "#6b7280",
    fontFamily: "Georgia, serif",
    layout: "two-column",
    headerStyle: "underline",
    skillsStyle: "list",
  },
  {
    id: "europeo",
    name: "Europeo",
    description: "Formato Europass standard",
    accentColor: "#0d9488",
    bgColor: "#f0fdfa",
    textColor: "#134e4a",
    secondaryText: "#5eead4",
    fontFamily: "Arial, Helvetica, sans-serif",
    layout: "two-column",
    headerStyle: "simple",
    skillsStyle: "grid",
  },
  {
    id: "creativo",
    name: "Creativo",
    description: "Design audace con impatto visivo",
    accentColor: "#ec4899",
    bgColor: "#1f1627",
    textColor: "#fdf2f8",
    secondaryText: "#f9a8d4",
    fontFamily: "Poppins, sans-serif",
    layout: "single-column",
    headerStyle: "highlight",
    skillsStyle: "badges",
  },
  {
    id: "ats",
    name: "ATS Friendly",
    description: "Ottimizzato per sistemi di tracciamento",
    accentColor: "#374151",
    bgColor: "#ffffff",
    textColor: "#111827",
    secondaryText: "#6b7280",
    fontFamily: "Arial, sans-serif",
    layout: "single-column",
    headerStyle: "minimal",
    skillsStyle: "plain",
  },
  {
    id: "accademico",
    name: "Accademico",
    description: "Ideale per ricercatori e docenti",
    accentColor: "#b45309",
    bgColor: "#fffbeb",
    textColor: "#451a03",
    secondaryText: "#d97706",
    fontFamily: "Times New Roman, serif",
    layout: "two-column",
    headerStyle: "classic",
    skillsStyle: "detailed",
  },
  {
    id: "minimal",
    name: "Minimal",
    description: "Essenziale e moderno",
    accentColor: "#000000",
    bgColor: "#fafafa",
    textColor: "#171717",
    secondaryText: "#525252",
    fontFamily: "Helvetica Neue, sans-serif",
    layout: "single-column",
    headerStyle: "plain",
    skillsStyle: "inline",
  },
  {
    id: "tech",
    name: "Tech",
    description: "Perfetto per ruoli tecnologici",
    accentColor: "#10b981",
    bgColor: "#0f172a",
    textColor: "#e2e8f0",
    secondaryText: "#94a3b8",
    fontFamily: "JetBrains Mono, monospace",
    layout: "single-column",
    headerStyle: "code-bar",
    skillsStyle: "chips",
  },
  {
    id: "harvard",
    name: "Harvard",
    description: "Stile elegante ispirato a Harvard University",
    accentColor: "#A41034",
    bgColor: "#ffffff",
    textColor: "#1a1a1a",
    secondaryText: "#666666",
    fontFamily: "Georgia, Times New Roman, serif",
    layout: "single-column",
    headerStyle: "classic-bar",
    skillsStyle: "minimal-lines",
  },
  {
    id: "oxford",
    name: "Oxford",
    description: "Design classico ispirato a Oxford University",
    accentColor: "#002147",
    bgColor: "#fafafa",
    textColor: "#1a1a1a",
    secondaryText: "#555555",
    fontFamily: "Garamond, Baskerville, serif",
    layout: "two-column",
    headerStyle: "elegant-underline",
    skillsStyle: "refined-list",
  },
  {
    id: "cambridge",
    name: "Cambridge",
    description: "Stile tradizionale ispirato a Cambridge University",
    accentColor: "#0A1E3D",
    bgColor: "#ffffff",
    textColor: "#1a1a1a",
    secondaryText: "#666666",
    fontFamily: "Palatino, Book Antiqua, serif",
    layout: "two-column",
    headerStyle: "royal-border",
    skillsStyle: "academic-grid",
  },
  {
    id: "stanford",
    name: "Stanford",
    description: "Moderno e pulito ispirato a Stanford University",
    accentColor: "#8C1515",
    bgColor: "#f9f9f9",
    textColor: "#2e2e2e",
    secondaryText: "#777777",
    fontFamily: "Source Sans Pro, Helvetica, sans-serif",
    layout: "single-column",
    headerStyle: "cardinal-header",
    skillsStyle: "clean-tags",
  },
  {
    id: "mit",
    name: "MIT",
    description: "Tecnico e professionale ispirato al MIT",
    accentColor: "#A31F34",
    bgColor: "#ffffff",
    textColor: "#333333",
    secondaryText: "#888888",
    fontFamily: "Roboto, Arial, sans-serif",
    layout: "single-column",
    headerStyle: "tech-line",
    skillsStyle: "inline-categories",
  },
  {
    id: "yale",
    name: "Yale",
    description: "Sofisticato e tradizionale ispirato a Yale University",
    accentColor: "#00356B",
    bgColor: "#fefefe",
    textColor: "#1a1a1a",
    secondaryText: "#5a5a5a",
    fontFamily: "Cambria, Hoefler Text, serif",
    layout: "two-column",
    headerStyle: "ivy-underline",
    skillsStyle: "bulleted-groups",
  },
  {
    id: "princeton",
    name: "Princeton",
    description: "Stile aristocratico ispirato a Princeton University",
    accentColor: "#E77500",
    bgColor: "#fffef9",
    textColor: "#1a1a1a",
    secondaryText: "#6b6b6b",
    fontFamily: "Adorn Serif, Georgia, serif",
    layout: "single-column",
    headerStyle: "orange-accent",
    skillsStyle: "elegant-tags",
  },
];

export const getTemplateById = (id: string): CVTemplate => {
  return cvTemplates.find((t) => t.id === id) || cvTemplates[0];
};

export const generateTemplateStyles = (templateId: string): { backgroundColor: string; color: string; fontFamily: string; accentColor: string; secondaryText: string } => {
  const template = getTemplateById(templateId);
  return {
    backgroundColor: template.bgColor,
    color: template.textColor,
    fontFamily: template.fontFamily,
    accentColor: template.accentColor,
    secondaryText: template.secondaryText,
  };
};
